### ISSUE TITLE
Create example modal

### ISSUE THREAD

**Issue by djrhoten** [djrhoten/CryptoCal#10]
Example modal needed so that our APIs can trigger those instead of alerts.

**Comment by djrhoten** [comment]
Example modal, first run, attached. 
[week-7-project copy.zip](https://github.com/djrhoten/CryptoCal/files/6208901/week-7-project.copy.zip)

**Comment by traveler2806** [comment]
Modal created and added to updated html/css skeleton as of 3/30/21.

**Comment by JosephSuvak** [comment]
Modal completed.
