### ISSUE TITLE
ReadMe/Presentation

### ISSUE THREAD

**Issue by djrhoten** [djrhoten/CryptoCal#6]
# Read Me
1. Introduction to app
2. Background into Crypto
3. FAQ/Site Functionality
4. Screenshots
4. Website link
5. Built by...

# Presentation

### CSS/Cardinal
-
-
### JavaScript/APIs
-
-

## Demo of website
-

**Comment by JosephSuvak** [comment]
Closing as the Presentation was Thursday. Good job on the Presentation DJ.
